"""Creacion de modelos

Revision ID: babc87ddd238
Revises: 
Create Date: 2025-07-07 03:45:21.090543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'babc87ddd238'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=50), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=50), nullable=True),
    sa.Column('primer_apellido', sa.String(length=50), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=50), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('enfermedades_cronicas', sa.String(length=200), nullable=True),
    sa.Column('alergias', sa.String(length=200), nullable=True),
    sa.Column('antecedentes_familiares', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfc', sa.String(length=15), nullable=False),
    sa.Column('primer_nombre', sa.String(length=50), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=50), nullable=True),
    sa.Column('primer_apellido', sa.String(length=50), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=50), nullable=True),
    sa.Column('cedula_profesional', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula_profesional'),
    sa.UniqueConstraint('rfc')
    )
    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('latidos_por_minuto', sa.Integer(), nullable=False),
    sa.Column('saturacion_oxigeno', sa.Float(), nullable=False),
    sa.Column('glucosa', sa.Float(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_medico'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medico_paciente',
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id_medico', 'id_paciente')
    )
    op.create_table('diagnosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('sintomas', sa.String(length=200), nullable=True),
    sa.Column('diagnostico', sa.String(length=200), nullable=True),
    sa.Column('tratamiento', sa.String(length=200), nullable=True),
    sa.Column('estudios_solicitados', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_cita'], ['citas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnosticos')
    op.drop_table('medico_paciente')
    op.drop_table('citas')
    op.drop_table('medicos')
    op.drop_table('roles')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
